language: node_js

node_js:
  # TODO: Once Node 8 LTS has been released, switch to it here.
  - "8.4"

sudo: false

env:
  global:
    - RACKET_DIR=~/racket
    - RACKET_RUN_COVERAGE=6.10
  matrix:
    - RACKET_VERSION=HEAD
    - RACKET_VERSION=RELEASE
    - RACKET_VERSION=6.10
    - RACKET_VERSION=6.7
    - RACKET_VERSION=6.4

matrix:
  allow_failures:
    - env: RACKET_VERSION=HEAD
    - env: RACKET_VERSION=RELEASE
    - node_js: "node"
  fast_finish: true

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - make setup
  - make setup-extra
  - raco pkg install --auto cover-codecov

script:
  - make unit-test
  - make integration-test

after_success:
  - if [ ${RACKET_RUN_COVERAGE} = ${RACKET_VERSION} ]; then
      COVERAGE_MODE=1 raco cover -bf codecov -d $TRAVIS_BUILD_DIR/coverage
        racketscript-compiler/racketscript/ tests/fixture.rkt;
    else
      echo "Skipping coverage.";
    fi

after_script:
